# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb: # | imagine_filter('meduim') 缩略图类型名
            quality: 75
            filters:
                thumbnail:
                    size: [360,230]
                    mode: outbound
        meduim: # | imagine_filter('meduim')
            quality: 75
            filters:
                thumbnail:
                    size: [800,440]
                    mode: outbound        

    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
