#config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

   
    mappings:
        property_image:
            uri_prefix: /images/properties # 图片的前缀
            upload_destination: '%kernel.project_dir%/public/images/properties' # 图片上传地址

             
            # delete_on_remove: default true, should the file be deleted when the entity is removed ;
            # delete_on_update: default true, should the file be deleted when a new file is uploaded ;
            # inject_on_load: default false, should the file be injected into the uploadable entity when it is loaded from the data store. The object will be an instance of Symfony\Component\HttpFoundation\File\File.
             
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # Vich\UploaderBundle\Naming\UniqidNamer
            # Vich\UploaderBundle\Naming\OrignameNamer
            # Vich\UploaderBundle\Naming\PropertyNamer
            # Vich\UploaderBundle\Naming\HashNamer
            # Vich\UploaderBundle\Naming\Base64Namer
            # Vich\UploaderBundle\Naming\SmartUniqueNamer
            # 命名 图片 https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md 


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
